# Generated by Django 5.1.15 on 2026-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_library", "0002_seed_industries"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prompt",
            new_name="prompt_libr_industr_a5bce8_idx",
            old_name="pl_prompt_idx",
        ),
        migrations.AlterField(
            model_name="industry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="promptsampleentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="promptsamplerun",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="promptvariation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
