# Generated by Django 5.1.15 on 2026-05-09 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_library", "0004_brandprompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryTrend",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("interest_over_time", models.JSONField(blank=True, default=list)),
                ("top_regions", models.JSONField(blank=True, default=list)),
                ("keyword_used", models.CharField(blank=True, max_length=120)),
                ("refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "industry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend",
                        to="prompt_library.industry",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_library_industrytrend",
            },
        ),
    ]
