# Generated by Django 5.1.15 on 2026-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt_library", "0005_industry_trend"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
    ]
