"""URL routes for the brand_vault REST API."""
from django.urls import path

from . import views

urlpatterns = [
    path(
        "websites/<uuid:website_id>/facts/",
        views.WebsiteFactsView.as_view(),
        name="brand-vault-website-facts",
    ),
    path(
        "websites/<uuid:website_id>/facts/bulk/",
        views.WebsiteBulkFactActionView.as_view(),
        name="brand-vault-website-facts-bulk",
    ),
    path(
        "websites/<uuid:website_id>/extract/",
        views.WebsiteExtractView.as_view(),
        name="brand-vault-website-extract",
    ),
    path(
        "websites/<uuid:website_id>/extract/status/",
        views.WebsiteExtractStatusView.as_view(),
        name="brand-vault-website-extract-status",
    ),
    path(
        "websites/<uuid:website_id>/stats/",
        views.WebsiteStatsView.as_view(),
        name="brand-vault-website-stats",
    ),
    path(
        "websites/<uuid:website_id>/contradictions/",
        views.WebsiteContradictionsView.as_view(),
        name="brand-vault-website-contradictions",
    ),
    path(
        "websites/<uuid:website_id>/coverage/",
        views.WebsiteCoverageView.as_view(),
        name="brand-vault-website-coverage",
    ),
    path(
        "websites/<uuid:website_id>/revisions/",
        views.WebsiteRevisionsView.as_view(),
        name="brand-vault-website-revisions",
    ),
    path(
        "websites/<uuid:website_id>/backlinks/",
        views.WebsiteBacklinksView.as_view(),
        name="brand-vault-website-backlinks",
    ),
    path(
        "websites/<uuid:website_id>/keywords/",
        views.WebsiteKeywordsView.as_view(),
        name="brand-vault-website-keywords",
    ),
    path(
        "facts/<uuid:fact_id>/",
        views.FactDetailView.as_view(),
        name="brand-vault-fact-detail",
    ),
    path(
        "facts/<uuid:fact_id>/usage/",
        views.FactUsageView.as_view(),
        name="brand-vault-fact-usage",
    ),
    path(
        "facts/<uuid:fact_id>/approve/",
        views.FactApproveView.as_view(),
        name="brand-vault-fact-approve",
    ),
    path(
        "facts/<uuid:fact_id>/reject/",
        views.FactRejectView.as_view(),
        name="brand-vault-fact-reject",
    ),
    path(
        "facts/<uuid:fact_id>/edit/",
        views.FactEditView.as_view(),
        name="brand-vault-fact-edit",
    ),
    path(
        "websites/<uuid:website_id>/facts/import/",
        views.WebsiteFactsImportView.as_view(),
        name="brand-vault-website-facts-import",
    ),
    path(
        "websites/<uuid:website_id>/facts/import-csv/",
        views.WebsiteFactsImportCSVView.as_view(),
        name="brand-vault-website-facts-import-csv",
    ),
    path(
        "websites/<uuid:website_id>/tone-samples/",
        views.WebsiteToneSamplesView.as_view(),
        name="brand-vault-website-tone-samples",
    ),
    path(
        "websites/<uuid:website_id>/tone-samples/create/",
        views.WebsiteToneSampleCreateView.as_view(),
        name="brand-vault-website-tone-sample-create",
    ),
    path(
        "tone-samples/<uuid:sample_id>/",
        views.ToneSampleDeleteView.as_view(),
        name="brand-vault-tone-sample-delete",
    ),
]
