# Generated by Django 5.1.15 on 2026-03-26 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="segment",
            field=models.CharField(
                choices=[("individual", "Individual"), ("enterprise", "Enterprise")],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="plan",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("enterprise", "Enterprise"),
                    ("starter", "Starter (Legacy)"),
                    ("growth", "Growth (Legacy)"),
                    ("scale", "Scale (Legacy)"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("enterprise", "Enterprise"),
                            ("starter", "Starter (Legacy)"),
                            ("growth", "Growth (Legacy)"),
                            ("scale", "Scale (Legacy)"),
                        ],
                        default="enterprise",
                        max_length=20,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_orgs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_organization",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_organizationmember",
                "unique_together": {("organization", "user")},
            },
        ),
    ]
