# Generated by Django 5.1.15 on 2026-04-13 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_organization_plan_alter_user_plan"),
        ("websites", "0004_website_onboarding_completed_platform_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITokenUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("lead_finder", "AI Lead Finder"),
                            ("agents", "AI Agents"),
                            ("messaging", "AI Messaging"),
                            ("llm_ranking", "LLM Ranking"),
                            ("seo_keywords", "SEO Keywords"),
                            ("analytics", "AI Insights"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI (GPT)"),
                            ("google", "Google (Gemini)"),
                        ],
                        default="anthropic",
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="e.g. claude-sonnet-4-20250514", max_length=80),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost in USD based on provider pricing",
                        max_digits=10,
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(default=0, help_text="How long the API call took in ms"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_usage",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_aitokenusage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "module", "created_at"],
                        name="accounts_ai_user_id_87f23f_idx",
                    ),
                    models.Index(fields=["created_at"], name="accounts_ai_created_197d70_idx"),
                ],
            },
        ),
    ]
