# Generated by Django 5.1.15 on 2026-08-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_resync_aitokenusage_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitokenusage',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='module',
            field=models.CharField(choices=[('llm_ranking', 'LLM Ranking'), ('rag', 'RAG / Embeddings'), ('onboarding', 'Onboarding scan'), ('prompt_library', 'Prompt Library'), ('agents', 'Hired Agents'), ('brand_vault', 'Brand Vault'), ('brand_security', 'Brand Security'), ('content_studio', 'Content Studio'), ('notifications', 'Notifications / Chat'), ('source_sentiment', 'Source Sentiment'), ('source_relevance', 'Source Relevance')], db_index=True, max_length=20),
        ),
    ]
