# Generated by Django 5.1.15 on 2026-08-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_aitokenusage_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('pro', 'Pro ($45/mo)'), ('business', 'Business (custom)'), ('individual', 'Individual (Legacy)'), ('enterprise', 'Enterprise (Legacy)'), ('starter', 'Starter (Legacy)'), ('growth', 'Growth (Legacy)'), ('scale', 'Scale (Legacy)')], default='enterprise', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('pro', 'Pro ($45/mo)'), ('business', 'Business (custom)'), ('individual', 'Individual (Legacy)'), ('enterprise', 'Enterprise (Legacy)'), ('starter', 'Starter (Legacy)'), ('growth', 'Growth (Legacy)'), ('scale', 'Scale (Legacy)')], default='individual', max_length=20),
        ),
    ]
