# Generated by Django 5.1.15 on 2026-08-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_organization_plan_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paywall_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='When the user chose the Free plan from the paywall. Null = never dismissed; clear to re-show the paywall.', null=True),
        ),
    ]
