# Generated by Django 5.1.15 on 2026-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_paywall_dismissed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitokenusage',
            name='module',
            field=models.CharField(choices=[('llm_ranking', 'LLM Ranking'), ('rag', 'RAG / Embeddings'), ('onboarding', 'Onboarding scan'), ('prompt_library', 'Prompt Library'), ('agents', 'Hired Agents'), ('brand_vault', 'Brand Vault'), ('brand_security', 'Brand Security'), ('content_studio', 'Content Studio'), ('notifications', 'Notifications / Chat'), ('source_sentiment', 'Source Sentiment'), ('source_relevance', 'Source Relevance'), ('brand_research', 'Brand Research')], db_index=True, max_length=20),
        ),
    ]
