# Generated by Django 5.1.15 on 2026-08-31 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_aitokenusage_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='require_sso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='session_max_age_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='joined_via',
            field=models.CharField(default='invite', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro ($45/mo)'), ('business', 'Business (custom)'), ('individual', 'Individual (Legacy)'), ('enterprise', 'Enterprise (Legacy)'), ('starter', 'Starter (Legacy)'), ('growth', 'Growth (Legacy)'), ('scale', 'Scale (Legacy)')], default='business', max_length=20),
        ),
        migrations.CreateModel(
            name='OrgDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('method', models.CharField(choices=[('dns_txt', 'DNS TXT record'), ('google_hd', 'Google Workspace hosted domain'), ('entra_tid', 'Microsoft Entra tenant'), ('manual', 'Manually verified')], default='dns_txt', max_length=20)),
                ('dns_token', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('auto_join', models.BooleanField(default=True)),
                ('entra_tenant_id', models.CharField(blank=True, max_length=64)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='accounts.organization')),
            ],
            options={
                'db_table': 'accounts_orgdomain',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organization')),
            ],
            options={
                'db_table': 'accounts_invitation',
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('organization', 'email'), name='uniq_pending_invite')],
            },
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('entra', 'Microsoft Entra')], max_length=20)),
                ('subject', models.CharField(max_length=190)),
                ('tenant', models.CharField(blank=True, default='', max_length=64)),
                ('email_at_link', models.EmailField(blank=True, max_length=254)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_socialidentity',
                'unique_together': {('provider', 'subject', 'tenant')},
            },
        ),
    ]
