# Generated by Django 5.1.15 on 2026-08-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organization_default_role_organization_require_sso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_prompts_per_audit',
            field=models.PositiveIntegerField(blank=True, help_text='Prompts per single run. Empty = plan default.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='monthly_prompt_allowance',
            field=models.IntegerField(blank=True, help_text='Prompts per member per month. -1 = unlimited. Empty = plan default.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='seat_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max members incl. pending invites. Empty = plan default.', null=True),
        ),
    ]
