# Generated by Django 5.1.15 on 2026-09-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_organization_max_prompts_per_audit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sso_connection_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='socialidentity',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('entra', 'Microsoft Entra'), ('saml', 'SAML (bridge)')], max_length=20),
        ),
    ]

