# Generated by Django 5.1.15 on 2026-04-13 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0004_website_onboarding_completed_platform_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInstruction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="Default Agent", max_length=120)),
                (
                    "instruction_text",
                    models.TextField(
                        help_text="Describe how the AI should behave, sell, qualify leads, etc."
                    ),
                ),
                (
                    "personality",
                    models.CharField(
                        default="professional",
                        help_text="Tone: professional, friendly, casual, assertive",
                        max_length=30,
                    ),
                ),
                (
                    "product_context",
                    models.TextField(
                        blank=True,
                        help_text="Products/services, pricing, USPs for the AI to reference",
                    ),
                ),
                (
                    "booking_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether the AI can book appointments in chat"
                    ),
                ),
                (
                    "auto_qualify",
                    models.BooleanField(
                        default=True, help_text="Whether the AI should score/qualify leads"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_instructions",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram DM"),
                            ("whatsapp", "WhatsApp"),
                            ("messenger", "Facebook Messenger"),
                            ("webchat", "Web Chat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "access_token",
                    models.TextField(blank=True, help_text="OAuth or API token for the channel"),
                ),
                (
                    "page_id",
                    models.CharField(
                        blank=True, help_text="Facebook Page ID / IG Business ID", max_length=120
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="WhatsApp phone number", max_length=20),
                ),
                ("webhook_secret", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messaging_channels",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("website", "channel_type")},
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_id",
                    models.CharField(help_text="Platform-specific user ID", max_length=255),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("avatar_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="AI-generated summary of this contact"),
                ),
                (
                    "lead_score",
                    models.IntegerField(default=0, help_text="0-100 lead quality score"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="messaging.channel",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messaging_contacts",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("channel", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("snoozed", "Snoozed"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "ai_enabled",
                    models.BooleanField(default=True, help_text="Whether AI auto-reply is active"),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_preview", models.CharField(blank=True, max_length=200)),
                ("unread_count", models.IntegerField(default=0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="messaging.channel",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="messaging.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")], max_length=10
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("voice", "Voice Note"),
                            ("file", "File"),
                            ("template", "Template"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True)),
                (
                    "sent_by",
                    models.CharField(
                        choices=[("human", "Human"), ("ai", "AI Agent"), ("system", "System")],
                        default="human",
                        max_length=10,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, help_text="Platform message ID", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "sent_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
