# Generated by Django 5.1.15 on 2026-04-13 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        ("websites", "0004_website_onboarding_completed_platform_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinstruction",
            name="instruction_text",
            field=models.TextField(
                blank=True,
                help_text="Legacy instruction text. Prefer AgentTrainingDoc for new content.",
            ),
        ),
        migrations.AlterField(
            model_name="aiinstruction",
            name="personality",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("friendly", "Friendly"),
                    ("casual", "Casual"),
                    ("assertive", "Assertive"),
                    ("bargaining", "Bargaining"),
                    ("empathetic", "Empathetic"),
                ],
                default="professional",
                help_text="Active tone the AI agent uses when responding",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="aiinstruction",
            name="product_context",
            field=models.TextField(
                blank=True,
                help_text="Legacy product context. Prefer AgentTrainingDoc for new content.",
            ),
        ),
        migrations.CreateModel(
            name="AgentTrainingDoc",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("persona", "Persona & Tone"),
                            ("product", "Product Knowledge"),
                            ("rules", "Rules & Objections"),
                            ("script", "Sales Script"),
                            ("faq", "FAQ"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Markdown content the AI agent uses as training context"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_training_docs",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
