# Generated by Django 5.1.15 on 2026-03-06 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("overall_score", models.IntegerField(blank=True, null=True)),
                ("seo_score", models.IntegerField(blank=True, null=True)),
                ("performance_score", models.IntegerField(blank=True, null=True)),
                ("mobile_score", models.IntegerField(blank=True, null=True)),
                ("security_score", models.IntegerField(blank=True, null=True)),
                ("content_score", models.IntegerField(blank=True, null=True)),
                ("report_url", models.URLField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "audits_audit",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("recommendation", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("element", models.CharField(blank=True, max_length=500)),
                ("impact_score", models.IntegerField(default=0)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="audits.audit",
                    ),
                ),
            ],
            options={
                "db_table": "audits_auditissue",
                "ordering": ["-impact_score", "severity"],
            },
        ),
        migrations.CreateModel(
            name="AuditSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "website",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_schedule",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "audits_auditschedule",
            },
        ),
    ]
