# Generated by Django 5.1.15 on 2026-03-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOGraderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('page_url', models.CharField(max_length=500)),
                ('original_value', models.TextField(blank=True, default='')),
                ('original_length', models.IntegerField(default=0)),
                ('suggested_fix', models.TextField(blank=True, default='')),
                ('suggested_length', models.IntegerField(default=0)),
                ('deployed', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grader_issues', to='audits.audit')),
            ],
            options={
                'db_table': 'audits_seograderissue',
                'ordering': ['category', 'page_url'],
            },
        ),
    ]
