# Generated by Django 5.1.15 on 2026-04-06 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0002_emailcampaign_campaignrecipient"),
        ("websites", "0004_website_onboarding_completed_platform_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("retell_agent_id", models.CharField(blank=True, max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                (
                    "greeting_message",
                    models.TextField(
                        default="Hello! Thank you for calling. How can I help you today?"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are a friendly and professional voice assistant. Help callers schedule appointments, answer questions about the business, and capture their contact information. Always confirm details before booking."
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=200)),
                (
                    "business_hours",
                    models.JSONField(
                        default=dict,
                        help_text="Business hours per day, e.g. {'monday': {'start': '09:00', 'end': '17:00'}}",
                    ),
                ),
                ("appointment_duration_minutes", models.IntegerField(default=30)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "website",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_agent_config",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "voice_agent_config",
            },
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_call_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External call identifier (Retell call_id, LiveKit room name, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="inbound",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ringing", "Ringing"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="ringing",
                        max_length=20,
                    ),
                ),
                ("caller_phone", models.CharField(db_index=True, max_length=30)),
                ("caller_name", models.CharField(blank=True, max_length=200)),
                ("caller_email", models.EmailField(blank=True, max_length=254)),
                ("caller_company", models.CharField(blank=True, max_length=200)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                (
                    "extracted_data",
                    models.JSONField(
                        default=dict,
                        help_text="Structured data extracted by AI (name, email, intent, etc.)",
                    ),
                ),
                ("call_intent", models.CharField(blank=True, max_length=100)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="leads.lead",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "voice_agent_calllog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caller_info",
                    models.JSONField(
                        default=dict,
                        help_text='{"name": "", "phone": "", "email": "", "company": ""}',
                    ),
                ),
                ("call_summary", models.TextField(blank=True)),
                (
                    "call_category",
                    models.CharField(
                        blank=True,
                        help_text="appointment, inquiry, complaint, support, sales, other",
                        max_length=30,
                    ),
                ),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                (
                    "follow_ups",
                    models.JSONField(
                        default=list,
                        help_text='[{"description": "", "urgency": "immediate|within_24h|this_week|no_rush"}]',
                    ),
                ),
                (
                    "appointments_detected",
                    models.JSONField(
                        default=list,
                        help_text='[{"date": "", "time": "", "description": "", "confirmed": false}]',
                    ),
                ),
                (
                    "raw_llm_output",
                    models.JSONField(
                        default=dict,
                        help_text="Full JSON output from the extraction LLM for debugging.",
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("processing_time_ms", models.IntegerField(default=0)),
                (
                    "call_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction",
                        to="voice_agent.calllog",
                    ),
                ),
            ],
            options={
                "db_table": "voice_agent_callextraction",
            },
        ),
        migrations.CreateModel(
            name="CallbackReminder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(max_length=30)),
                ("reason", models.TextField(blank=True)),
                ("remind_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("completed", "Completed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="callback_reminders",
                        to="websites.website",
                    ),
                ),
                (
                    "call_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_reminders",
                        to="voice_agent.calllog",
                    ),
                ),
            ],
            options={
                "db_table": "voice_agent_callbackreminder",
                "ordering": ["remind_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("attendee_name", models.CharField(max_length=200)),
                ("attendee_phone", models.CharField(max_length=30)),
                ("attendee_email", models.EmailField(blank=True, max_length=254)),
                ("google_event_id", models.CharField(blank=True, max_length=200)),
                ("outlook_event_id", models.CharField(blank=True, max_length=200)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="websites.website",
                    ),
                ),
                (
                    "call_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="voice_agent.calllog",
                    ),
                ),
            ],
            options={
                "db_table": "voice_agent_calendarevent",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="CallTodo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_todos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "call_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="voice_agent.calllog",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_todos",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "voice_agent_calltodo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(fields=["website", "status"], name="voice_agent_website_5ebb51_idx"),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["website", "caller_phone"], name="voice_agent_website_968a6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["website", "-created_at"], name="voice_agent_website_dbbdcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callbackreminder",
            index=models.Index(
                fields=["website", "status", "remind_at"], name="voice_agent_website_38be20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["website", "start_time"], name="voice_agent_website_fb8525_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["website", "status"], name="voice_agent_website_218771_idx"),
        ),
        migrations.AddIndex(
            model_name="calltodo",
            index=models.Index(fields=["website", "status"], name="voice_agent_website_baef42_idx"),
        ),
        migrations.AddIndex(
            model_name="calltodo",
            index=models.Index(
                fields=["website", "priority", "status"], name="voice_agent_website_f8ddc6_idx"
            ),
        ),
    ]
