# Generated by Django 5.1.15 on 2026-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_agent", "0006_voice_usage"),
        ("websites", "0004_website_onboarding_completed_platform_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="phonenumber",
            name="unique_website_number",
        ),
        migrations.RenameIndex(
            model_name="callcampaign",
            new_name="voice_agent_website_4d201f_idx",
            old_name="va_camp_web_status_idx",
        ),
        migrations.RenameIndex(
            model_name="calltarget",
            new_name="voice_agent_campaig_9b296b_idx",
            old_name="va_target_camp_status_idx",
        ),
        migrations.RenameIndex(
            model_name="phoneverification",
            new_name="voice_agent_website_468c23_idx",
            old_name="va_phv_web_num_status_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceusagemonthly",
            new_name="voice_agent_website_777b39_idx",
            old_name="va_usage_web_ym_idx",
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="business_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown knowledge base about the business — services, pricing, FAQs, policies, etc.",
            ),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="forwarding_number",
            field=models.CharField(
                blank=True,
                help_text="The SIP/Telnyx number that the business forwards their calls to.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="calltarget",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom fields imported from CSV (e.g. company, product interest).",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phonenumber",
            unique_together={("website", "number")},
        ),
    ]
