# Generated by Django 5.1.15 on 2026-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "llm_ranking",
            "0002_rename_llm_result_audit_provider_idx_llm_ranking_audit_i_4b3267_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrankingaudit",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="llmrankingaudit",
            name="queries_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmrankingaudit",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmrankingaudit",
            name="total_queries",
            field=models.IntegerField(default=0),
        ),
    ]
