# Generated by Django 5.1.15 on 2026-04-15 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ranking", "0003_llmrankingaudit_location_and_more"),
        ("websites", "0004_website_onboarding_completed_platform_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMRankingSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 Weeks"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("business_description", models.TextField(blank=True)),
                ("industry", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("keywords", models.JSONField(default=list)),
                (
                    "providers",
                    models.JSONField(
                        default=list, help_text="LLM providers to query. Empty = all."
                    ),
                ),
                ("next_run_at", models.DateTimeField(db_index=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_ranking_schedule",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "llm_ranking_schedule",
            },
        ),
    ]
