# Generated by Django 5.1.15 on 2026-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_ranking', '0004_llm_ranking_extraction_and_cis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmrankingresult',
            name='provider',
            field=models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('gpt4', 'GPT-4 (OpenAI)'), ('gemini', 'Gemini (Google)'), ('perplexity', 'Perplexity'), ('meta_llama', 'Meta Llama'), ('mistral', 'Mistral AI'), ('cohere', 'Cohere'), ('deepseek', 'DeepSeek'), ('grok', 'Grok (xAI)'), ('amazon_nova', 'Amazon Nova')], db_index=True, max_length=30),
        ),
    ]
