# Generated by Django 5.1.15 on 2026-04-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ranking", "0004_add_llmrankingschedule"),
        ("llm_ranking", "0004_llm_ranking_extraction_and_cis"),
    ]

    operations = []
