# Generated by Django 5.1.15 on 2026-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_ranking', '0005_alter_llmrankingresult_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmrankingaudit',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmrankingaudit',
            name='schedule_frequency',
            field=models.CharField(blank=True, choices=[('', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', max_length=20),
        ),
    ]
