# Generated by Django 5.1.15 on 2026-04-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ranking", "0005_merge_20260424_1557"),
        ("llm_ranking", "0006_add_duration_and_schedule"),
    ]

    operations = []
