# Generated by Django 5.1.15 on 2026-04-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ranking", "0007_merge_20260425_1951"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrankingaudit",
            name="context_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
