# Generated by Django 5.1.15 on 2026-04-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ranking", "0008_add_context_urls_to_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrankingaudit",
            name="audit_logs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
