# Generated by Django 5.1.15 on 2026-08-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_ranking', '0021_result_unique_includes_model_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelTestRun',
        ),
    ]
