# Generated by Django 5.1.15 on 2026-03-06 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("competitor_url", models.URLField(max_length=500)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("auto_detected", models.BooleanField(default=False)),
                ("estimated_traffic", models.IntegerField(blank=True, null=True)),
                ("domain_authority", models.IntegerField(blank=True, null=True)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "competitors_competitor",
                "unique_together": {("website", "competitor_url")},
            },
        ),
        migrations.CreateModel(
            name="CompetitorChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("new_page", "New Page"),
                            ("removed_page", "Removed Page"),
                            ("ranking_change", "Ranking Change"),
                            ("content_update", "Content Update"),
                            ("pricing_change", "Pricing Change"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detail", models.JSONField(default=dict)),
                ("detected_at", models.DateTimeField(db_index=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="competitors.competitor",
                    ),
                ),
            ],
            options={
                "db_table": "competitors_competitorchange",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("traffic_estimate", models.IntegerField(null=True)),
                ("keyword_count", models.IntegerField(null=True)),
                ("backlink_count", models.IntegerField(null=True)),
                ("content_count", models.IntegerField(null=True)),
                ("metrics", models.JSONField(default=dict)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="competitors.competitor",
                    ),
                ),
            ],
            options={
                "db_table": "competitors_competitorsnapshot",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="KeywordGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(db_index=True, max_length=500)),
                ("your_rank", models.IntegerField(blank=True, null=True)),
                ("competitor_ranks", models.JSONField(default=dict)),
                ("search_volume", models.IntegerField(null=True)),
                ("difficulty", models.IntegerField(null=True)),
                ("opportunity_score", models.FloatField(default=0)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_gaps",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "competitors_keywordgap",
                "unique_together": {("website", "keyword")},
            },
        ),
    ]
