# Generated by Django 5.1.15 on 2026-03-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("starter", "Starter"), ("growth", "Growth"), ("scale", "Scale")],
                        default="starter",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("trialing", "Trialing"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscription",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_invoice_id", models.CharField(max_length=100, unique=True)),
                ("amount_paid", models.IntegerField(default=0)),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("status", models.CharField(max_length=20)),
                ("invoice_pdf", models.URLField(blank=True)),
                ("period_start", models.DateTimeField(null=True)),
                ("period_end", models.DateTimeField(null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "billing_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("pageviews", "Page Views"),
                            ("audits", "Audits"),
                            ("ai_calls", "AI Calls"),
                            ("leads", "Leads"),
                        ],
                        max_length=30,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "billing_usagerecord",
                "unique_together": {("subscription", "metric", "period_start")},
            },
        ),
    ]
