# Generated by Django 5.1.15 on 2026-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("enterprise", "Enterprise"),
                    ("starter", "Starter (Legacy)"),
                    ("growth", "Growth (Legacy)"),
                    ("scale", "Scale (Legacy)"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_event_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, default="")),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "billing_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"], name="billing_eve_event_t_990dd1_idx"
                    ),
                    models.Index(
                        fields=["processed", "-created_at"], name="billing_eve_process_4850d2_idx"
                    ),
                ],
            },
        ),
    ]
