# Generated by Django 5.1.15 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_subscription_plan_billingevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("enterprise", "Enterprise"),
                    ("individual", "Individual (Legacy)"),
                    ("growth", "Growth (Legacy)"),
                    ("scale", "Scale (Legacy)"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
    ]
