# Generated by Django 5.1.15 on 2026-04-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter ($29/mo)'), ('pro', 'Pro ($96/mo)'), ('enterprise', 'Enterprise'), ('individual', 'Individual (Legacy)'), ('growth', 'Growth (Legacy)'), ('scale', 'Scale (Legacy)')], default='starter', max_length=20),
        ),
    ]
