# Generated by Django 5.1.15 on 2026-08-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_subscription_plan_three_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='polar_subscription_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('pro', 'Pro ($45/mo)'), ('business', 'Business (custom)'), ('individual', 'Individual (Legacy)'), ('enterprise', 'Enterprise (Legacy)'), ('starter', 'Starter (Legacy)'), ('growth', 'Growth (Legacy)'), ('scale', 'Scale (Legacy)')], default='individual', max_length=20),
        ),
    ]
