# Generated by Django 5.1.15 on 2026-08-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_subscription_polar_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro ($45/mo)'), ('business', 'Business (custom)'), ('individual', 'Individual (Legacy)'), ('enterprise', 'Enterprise (Legacy)'), ('starter', 'Starter (Legacy)'), ('growth', 'Growth (Legacy)'), ('scale', 'Scale (Legacy)')], default='individual', max_length=20),
        ),
    ]
