# Generated by Django 5.1.15 on 2026-08-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
