# Generated by Django 5.1.15 on 2026-08-20 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_aitokenusage_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polar_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('environment', models.CharField(default='sandbox', max_length=12)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polar_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metering_polar_customer',
            },
        ),
        migrations.CreateModel(
            name='PolarEventOutbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('external_customer_id', models.CharField(max_length=64)),
                ('name', models.CharField(default='llm_usage', max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dead', 'Dead')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('usage', models.OneToOneField(blank=True, help_text='Source ledger row; SET_NULL so ledger pruning never blocks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polar_outbox', to='accounts.aitokenusage')),
            ],
            options={
                'verbose_name_plural': 'polar event outbox',
                'db_table': 'metering_polar_event_outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='metering_po_status_e870d0_idx')],
            },
        ),
    ]
