from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initial migration for the stub `leads` app. The two models exist
    only to satisfy historical lazy ForeignKey references in
    `analytics` migrations (FKs were removed in analytics.0008).
    Both are `managed = False`, so no DDL is emitted.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={"db_table": "leads_emailcampaign", "managed": False},
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={"db_table": "leads_campaignrecipient", "managed": False},
        ),
        # managed=False emits no DDL, but historical analytics migrations
        # (0003) create real FK constraints against these tables, so a
        # database migrated from scratch needs them to physically exist.
        # Long-lived environments already have them; IF NOT EXISTS makes
        # this a no-op there.
        migrations.RunSQL(
            sql=(
                "CREATE TABLE IF NOT EXISTS leads_emailcampaign "
                "(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY); "
                "CREATE TABLE IF NOT EXISTS leads_campaignrecipient "
                "(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
