# Generated by Django 5.1.15 on 2026-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_emailcampaign_campaignrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrecipient",
            name="variant",
            field=models.CharField(
                choices=[("A", "Variant A"), ("B", "Variant B")], default="A", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="ab_split_ratio",
            field=models.IntegerField(
                default=50, help_text="Percentage of recipients assigned to variant A (rest get B)"
            ),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="body_b",
            field=models.TextField(blank=True, help_text="Variant B body content (A/B test)"),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="is_ab_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="subject_b",
            field=models.CharField(
                blank=True, help_text="Variant B subject line (A/B test)", max_length=500
            ),
        ),
    ]
