# Generated by Django 5.1.15 on 2026-04-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_ab_testing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="from_email",
            field=models.CharField(blank=True, help_text="Sender email address", max_length=254),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="from_name",
            field=models.CharField(blank=True, help_text="Sender display name", max_length=200),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="name",
            field=models.CharField(blank=True, help_text="Internal campaign name", max_length=200),
        ),
    ]
