# Generated by Django 5.1.15 on 2026-08-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_created_at_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='recorded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='source_app',
            field=models.CharField(choices=[('brand_input', 'Brand input'), ('llm_response', 'AI answers'), ('security_alert', 'Security findings'), ('agent_insight', 'Agent insights'), ('search_queries', 'Search queries'), ('citations', 'Citations'), ('prompt_notes', 'Prompt notes')], db_index=True, default='brand_input', max_length=24),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='source_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
