# Generated by Django 5.1.15 on 2026-08-30 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_knowledgechunk_metadata_knowledgechunk_recorded_at_and_more'),
        ('websites', '0009_rebrand_integration_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCrawlConsent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_seeded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_crawl_consents', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_crawl_consents', to='websites.website')),
            ],
            options={
                'db_table': 'rag_agent_crawl_consent',
                'constraints': [models.UniqueConstraint(fields=('user', 'website'), name='uq_rag_agent_crawl_user_website')],
            },
        ),
    ]
