# Generated by Django 5.1.15 on 2026-08-31 01:33
#
# Org-shared knowledge base: uniqueness moves from (user, website[, url])
# to website-level keys. The knowledge base belongs to the project, not
# the person who added it; ``user`` stays as attribution only.

from django.conf import settings
from django.db import migrations, models


def check_no_website_level_duplicates(apps, schema_editor):
    """Abort before tightening the constraints if any duplicates exist.

    Historically each website had exactly one user, so no (website, url)
    pair should appear on more than one KnowledgeSource row and no
    website should hold more than one AgentCrawlConsent row. If that
    assumption is wrong for a deployment, fail loudly with the offending
    keys instead of letting AddConstraint raise an opaque IntegrityError
    mid-migration.
    """
    from django.db.models import Count

    KnowledgeSource = apps.get_model("rag", "KnowledgeSource")
    AgentCrawlConsent = apps.get_model("rag", "AgentCrawlConsent")

    dupe_sources = list(
        KnowledgeSource.objects.values("website_id", "url")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    if dupe_sources:
        sample = ", ".join(
            f"(website={d['website_id']}, url={d['url'][:80]}, rows={d['n']})"
            for d in dupe_sources[:10]
        )
        raise RuntimeError(
            "Cannot make KnowledgeSource unique on (website, url): "
            f"{len(dupe_sources)} duplicate pair(s) exist. "
            "Merge or delete the duplicate rows, then re-run the "
            f"migration. First offenders: {sample}"
        )

    dupe_consents = list(
        AgentCrawlConsent.objects.values("website_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    if dupe_consents:
        sample = ", ".join(
            f"(website={d['website_id']}, rows={d['n']})"
            for d in dupe_consents[:10]
        )
        raise RuntimeError(
            "Cannot make AgentCrawlConsent unique on (website): "
            f"{len(dupe_consents)} website(s) hold multiple consent rows. "
            "Keep one row per website (prefer the enabled one), then "
            f"re-run the migration. First offenders: {sample}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_agentcrawlconsent'),
        ('websites', '0010_alter_website_unique_together_website_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            check_no_website_level_duplicates,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='agentcrawlconsent',
            name='uq_rag_agent_crawl_user_website',
        ),
        migrations.RemoveConstraint(
            model_name='knowledgesource',
            name='uq_rag_source_user_website_url',
        ),
        migrations.AddConstraint(
            model_name='agentcrawlconsent',
            constraint=models.UniqueConstraint(fields=('website',), name='uq_rag_agent_crawl_website'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('website', 'url'), name='uq_rag_source_website_url'),
        ),
    ]
