# Generated by Django 5.1.15 on 2026-03-27 00:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_email", models.CharField(blank=True, default="", max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=300)),
                (
                    "event",
                    models.CharField(
                        db_index=True,
                        help_text="Dot-notation event name, e.g. 'user.login', 'billing.checkout_created'",
                        max_length=120,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("api_call", "API Call"),
                            ("webhook", "Webhook"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="api_call",
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of resource affected, e.g. 'subscription', 'website', 'lead'",
                        max_length=80,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID of the affected resource",
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("path", models.CharField(blank=True, default="", max_length=500)),
                ("request_id", models.CharField(blank=True, default="", max_length=50)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context. NEVER include PII, passwords, or sensitive data.",
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "compliance_audit_log",
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
                "indexes": [
                    models.Index(
                        fields=["user_id", "-timestamp"], name="compliance__user_id_e38072_idx"
                    ),
                    models.Index(
                        fields=["event", "-timestamp"], name="compliance__event_93f703_idx"
                    ),
                    models.Index(
                        fields=["action", "-timestamp"], name="compliance__action_6409e0_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="compliance__resourc_bb2fa9_idx",
                    ),
                    models.Index(
                        fields=["-timestamp", "success"], name="compliance__timesta_82f87c_idx"
                    ),
                ],
            },
        ),
    ]
