# Generated by Django 5.1.15 on 2026-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_leads", "0001_initial"),
        ("websites", "0004_website_onboarding_completed_platform_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="socialleadsource",
            name="unique_website_platform_form",
        ),
        migrations.RenameIndex(
            model_name="sociallead",
            new_name="social_lead_website_64ae50_idx",
            old_name="soc_lead_website_processed_idx",
        ),
        migrations.RenameIndex(
            model_name="sociallead",
            new_name="social_lead_source__761e5a_idx",
            old_name="soc_lead_source_ext_idx",
        ),
        migrations.AlterField(
            model_name="sociallead",
            name="external_lead_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Platform-assigned lead ID (prevents duplicate imports)",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="sociallead",
            name="form_data",
            field=models.JSONField(
                default=dict, help_text="Raw field responses from the lead form."
            ),
        ),
        migrations.AlterField(
            model_name="sociallead",
            name="is_processed",
            field=models.BooleanField(
                default=False, help_text="Whether a Lead record has been created."
            ),
        ),
        migrations.AlterField(
            model_name="socialleadsource",
            name="access_token",
            field=models.TextField(blank=True, help_text="OAuth access token"),
        ),
        migrations.AlterField(
            model_name="socialleadsource",
            name="account_id",
            field=models.CharField(
                blank=True, help_text="Ad account ID or page ID", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="socialleadsource",
            name="form_id",
            field=models.CharField(
                blank=True, help_text="Lead form / lead gen form ID", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="socialleadsource",
            name="label",
            field=models.CharField(
                blank=True, help_text="e.g. 'Facebook - Summer Campaign'", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="socialleadsource",
            name="webhook_verify_token",
            field=models.CharField(
                blank=True,
                help_text="Random token used to verify webhook ownership (Facebook hub.verify_token)",
                max_length=200,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialleadsource",
            unique_together={("website", "platform", "form_id")},
        ),
    ]
