# Generated by Django 5.1.15 on 2026-06-26 00:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0002_integrationconnection"),
        ("websites", "0007_website_competitors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HiredAgent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("agent_key", models.CharField(db_index=True, max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("schedule_time", models.TimeField(default="09:00")),
                (
                    "next_run_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("auto_pause_threshold", models.IntegerField(default=3)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slack_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hired_agents",
                        to="notifications.integrationconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hired_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hired_agents",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "agents_hiredagent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(choices=[("user", "User"), ("agent", "Agent")], max_length=16),
                ),
                ("text", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-app"), ("slack", "Slack")],
                        default="in_app",
                        max_length=16,
                    ),
                ),
                ("slack_ts", models.CharField(blank=True, max_length=40)),
                ("thread_ts", models.CharField(blank=True, max_length=40)),
                (
                    "hired_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.hiredagent",
                    ),
                ),
            ],
            options={
                "db_table": "agents_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentInsight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("run_date", models.DateField(db_index=True)),
                ("title", models.CharField(max_length=300)),
                ("summary_markdown", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("source_refs", models.JSONField(blank=True, default=list)),
                ("delivered_channels", models.JSONField(blank=True, default=list)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                (
                    "hired_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="agents.hiredagent",
                    ),
                ),
            ],
            options={
                "db_table": "agents_insight",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action_type", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(max_length=300)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=12,
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="agents.agentinsight",
                    ),
                ),
                (
                    "hired_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="agents.hiredagent",
                    ),
                ),
            ],
            options={
                "db_table": "agents_action",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hiredagent",
            index=models.Index(
                fields=["is_active", "next_run_at"], name="agents_hire_is_acti_a153c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hiredagent",
            index=models.Index(fields=["user", "website"], name="agents_hire_user_id_b76ddc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="hiredagent",
            unique_together={("website", "agent_key")},
        ),
        migrations.AddIndex(
            model_name="agentmessage",
            index=models.Index(
                fields=["hired_agent", "created_at"], name="agents_mess_hired_a_f6030b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentinsight",
            index=models.Index(
                fields=["hired_agent", "-created_at"], name="agents_insi_hired_a_c19ac3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentaction",
            index=models.Index(
                fields=["hired_agent", "status"], name="agents_acti_hired_a_f1ba33_idx"
            ),
        ),
    ]
