# Generated by Django 5.1.15 on 2026-03-08 02:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("opportunity_finder", "Opportunity Finder"),
                            ("campaign_runner", "Campaign Runner"),
                            ("competitor_watcher", "Competitor Watcher"),
                            ("anomaly_responder", "Anomaly Responder"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused — Awaiting Approval"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("event", "Event-Triggered"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of what the agent did"
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        blank=True, default=list, help_text="Structured findings/recommendations"
                    ),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "approval_request",
                    models.TextField(blank=True, help_text="What the agent is asking approval for"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("steps_count", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agentrun",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("reasoning", models.TextField(help_text="Why the agent chose this action")),
                ("tool_name", models.CharField(max_length=100)),
                ("tool_params", models.JSONField(default=dict)),
                ("tool_result", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agentstep",
                "ordering": ["step_number"],
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["website", "-created_at"], name="agents_agen_website_e132ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["agent_type", "status"], name="agents_agen_agent_t_53b5de_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentstep",
            unique_together={("agent_run", "step_number")},
        ),
    ]
