# Generated by Django 5.1.15 on 2026-08-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmessage',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('slack', 'Slack'), ('discord', 'Discord')], default='in_app', max_length=16),
        ),
    ]
