# Generated by Django 5.1.15 on 2026-08-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='model',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
