# Generated by Django 5.1.15 on 2026-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_webhookendpoint_integration_new_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='integration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
