# Generated by Django 5.1.15 on 2026-03-23 12:29
# These fields already exist in the DB — this migration records the state.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_integration_last_synced_at_integration_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('shopify', 'Shopify'), ('wordpress', 'WordPress'), ('woocommerce', 'WooCommerce'), ('custom', 'Custom / Other')], default='custom', max_length=20),
        ),
    ]
