# Generated by Django 5.1.15 on 2026-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0004_website_onboarding_completed_platform_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="description",
            field=models.TextField(
                blank=True, help_text="Business description for AI visibility analysis"
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="topics",
            field=models.JSONField(
                blank=True, default=list, help_text="Selected AI visibility topics/categories"
            ),
        ),
    ]
