# Generated by Django 5.1.15 on 2026-08-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_website_competitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('ga', 'Google Analytics'), ('ga_hosted', 'FetchBot Google tag'), ('cloudflare', 'Cloudflare'), ('gsc', 'Google Search Console'), ('facebook', 'Facebook Ads'), ('shopify', 'Shopify'), ('mailchimp', 'Mailchimp'), ('google_drive', 'Google Drive'), ('canva', 'Canva'), ('hubspot', 'HubSpot')], max_length=20),
        ),
    ]
