# Generated by Django 5.1.15 on 2026-08-31, then hand-ordered:
# the tenant-scoped constraints are created BEFORE the legacy (user, url)
# unique_together drops, so there is no window in which duplicate projects
# can be written. Both adds are provably satisfiable on existing data —
# every pre-existing row has organization NULL and already satisfied
# (user, url) — but the RunPython pre-check asserts that instead of
# assuming it (historical soft-delete edge cases would surface here as a
# clean abort rather than a constraint error mid-migration).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _assert_no_duplicate_urls(apps, schema_editor):
    Website = apps.get_model("websites", "Website")
    dupes = (
        Website.objects.values("user_id", "url")
        .annotate(n=models.Count("id"))
        .filter(n__gt=1)
        # .first() on an unordered aggregate is a TypeError on Django 5.
        .order_by("user_id")
    )
    first = dupes.first()
    if first:
        raise RuntimeError(
            "websites_website holds duplicate (user, url) rows "
            f"(e.g. user={first['user_id']} url={first['url']!r}); resolve "
            "them before applying the tenant-scoped unique constraints."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organization_default_role_organization_require_sso_and_more'),
        ('websites', '0009_rebrand_integration_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_assert_no_duplicate_urls, migrations.RunPython.noop),
        migrations.AddField(
            model_name='website',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('user', 'url'), name='uniq_personal_site_url'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'url'), name='uniq_org_site_url'),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together=set(),
        ),
    ]
