# Generated by Django 5.1.15 on 2026-07-09 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand_vault", "0003_safety"),
        ("websites", "0007_website_competitors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandSecurityAgent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("agent_id", models.CharField(max_length=40)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[("idle", "Idle"), ("running", "Running"), ("error", "Error")],
                        default="idle",
                        max_length=10,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "brand_vault_securityagent",
            },
        ),
        migrations.CreateModel(
            name="BrandSecurityConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("brand_terms", models.JSONField(blank=True, default=list)),
                ("negative_keywords", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "brand_vault_securityconfig",
            },
        ),
        migrations.AddField(
            model_name="safetyalert",
            name="agent_id",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name="safetyalert",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="safetyalert",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("llm", "LLM"),
                    ("serp", "SERP"),
                    ("reddit", "Reddit"),
                    ("x", "X"),
                    ("trends", "Google Trends"),
                    ("web", "Web"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="safetyalert",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="safetyalert",
            name="title",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="safetyalert",
            name="issue",
            field=models.CharField(
                choices=[
                    ("hallucination", "Hallucination"),
                    ("unverified", "Unverified claim"),
                    ("outdated", "Outdated info"),
                    ("harmful", "Harmful mention"),
                    ("negative", "Negative mention"),
                    ("emerging_narrative", "Emerging narrative"),
                    ("negative_outranking", "Negative page outranking"),
                    ("ranking_for_bad_query", "Ranking for negative query"),
                    ("sge_misrepresentation", "AI Overview misrepresentation"),
                    ("sentiment_drop", "Sentiment drop"),
                    ("impersonation", "Impersonation"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="safetyalert",
            name="model",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="safetyalert",
            name="prompt_text",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="safetyalert",
            index=models.Index(fields=["website", "agent_id", "status"], name="bv_sa_w_a_s_idx"),
        ),
        migrations.AddField(
            model_name="brandsecurityagent",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_agents",
                to="websites.website",
            ),
        ),
        migrations.AddField(
            model_name="brandsecurityconfig",
            name="website",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_config",
                to="websites.website",
            ),
        ),
        migrations.AddIndex(
            model_name="brandsecurityagent",
            index=models.Index(fields=["website", "enabled"], name="bv_sag_w_en_idx"),
        ),
        migrations.AddIndex(
            model_name="brandsecurityagent",
            index=models.Index(fields=["enabled", "next_run_at"], name="bv_sag_en_nr_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="brandsecurityagent",
            unique_together={("website", "agent_id")},
        ),
    ]
