# Generated by Django 5.1.15 on 2026-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand_vault", "0006_safetyalert_evidence_chunks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandsecurityagent",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("error", "Error"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
    ]
