# Generated by Django 5.1.15 on 2026-09-01 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_vault', '0012_alter_safetyalert_issue'),
        ('websites', '0010_alter_website_unique_together_website_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPulse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('auto_scan', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('last_digest_at', models.DateTimeField(blank=True, null=True)),
                ('last_alert_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_scan_queued_at', models.DateTimeField(blank=True, null=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pulse', to='websites.website')),
            ],
            options={
                'db_table': 'brand_vault_brandpulse',
            },
        ),
    ]
