# Generated by Django 5.1.15 on 2026-07-03 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0007_website_competitors"),
    ]

    operations = [
        migrations.CreateModel(
            name="GscDailyTotal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("position", models.FloatField(default=0.0)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_daily_totals",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "search_console_dailytotal",
                "indexes": [
                    models.Index(fields=["website", "date"], name="search_cons_website_4dd413_idx")
                ],
                "unique_together": {("website", "date")},
            },
        ),
        migrations.CreateModel(
            name="GscPageStat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("position", models.FloatField(default=0.0)),
                ("page", models.CharField(max_length=1000)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_page_stats",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "search_console_pagestat",
                "indexes": [
                    models.Index(fields=["website", "date"], name="search_cons_website_606f83_idx")
                ],
                "unique_together": {("website", "date", "page")},
            },
        ),
        migrations.CreateModel(
            name="GscQueryStat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("position", models.FloatField(default=0.0)),
                ("query", models.CharField(max_length=512)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_query_stats",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "search_console_querystat",
                "indexes": [
                    models.Index(fields=["website", "date"], name="search_cons_website_ec0b14_idx"),
                    models.Index(
                        fields=["website", "query", "date"], name="search_cons_website_77190c_idx"
                    ),
                ],
                "unique_together": {("website", "date", "query")},
            },
        ),
    ]
