# Generated by Django 5.1.15 on 2026-03-06 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("steps", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funnels",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_customfunnel",
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fingerprint_hash", models.CharField(db_index=True, max_length=64)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("geo_country", models.CharField(blank=True, max_length=2)),
                ("geo_city", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("first_seen", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                ("visit_count", models.PositiveIntegerField(default=1)),
                ("lead_score", models.IntegerField(db_index=True, default=0)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_visitor",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("entry_page", models.URLField(blank=True, max_length=1000)),
                ("exit_page", models.URLField(blank=True, max_length=1000)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("medium", models.CharField(blank=True, max_length=100)),
                ("campaign", models.CharField(blank=True, max_length=200)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="analytics.visitor",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_session",
            },
        ),
        migrations.CreateModel(
            name="PageEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("referrer", models.URLField(blank=True, max_length=2000)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pageview", "Page View"),
                            ("click", "Click"),
                            ("form_submit", "Form Submit"),
                            ("scroll", "Scroll"),
                            ("custom", "Custom"),
                        ],
                        default="pageview",
                        max_length=20,
                    ),
                ),
                ("event_name", models.CharField(blank=True, max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("scroll_depth", models.IntegerField(blank=True, null=True)),
                ("time_on_page_ms", models.IntegerField(blank=True, null=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="websites.website",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="analytics.session",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.visitor",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_pageevent",
            },
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["website", "lead_score"], name="analytics_v_website_5c07d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["website", "last_seen"], name="analytics_v_website_fdcc7c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visitor",
            unique_together={("website", "fingerprint_hash")},
        ),
        migrations.AddIndex(
            model_name="pageevent",
            index=models.Index(
                fields=["website", "event_type", "timestamp"], name="analytics_p_website_79cb5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageevent",
            index=models.Index(
                fields=["visitor", "timestamp"], name="analytics_p_visitor_072367_idx"
            ),
        ),
    ]
