# Generated by Django 5.1.15 on 2026-03-06 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedKeyword",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("keyword", models.CharField(db_index=True, max_length=300)),
                ("target_url", models.URLField(blank=True, max_length=2000)),
                ("current_rank", models.IntegerField(blank=True, null=True)),
                ("previous_rank", models.IntegerField(blank=True, null=True)),
                ("best_rank", models.IntegerField(blank=True, null=True)),
                ("search_volume", models.IntegerField(default=0)),
                ("difficulty", models.IntegerField(default=0)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_keywords",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_trackedkeyword",
                "unique_together": {("website", "keyword")},
            },
        ),
        migrations.CreateModel(
            name="KeywordRankHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(db_index=True)),
                ("serp_features", models.JSONField(blank=True, default=list)),
                (
                    "tracked_keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="analytics.trackedkeyword",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_keywordrankhistory",
                "ordering": ["-date"],
                "unique_together": {("tracked_keyword", "date")},
            },
        ),
    ]
