# Generated by Django 5.1.15 on 2026-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_trackedlink_linkclick'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='linkclick',
            new_name='analytics_l_tracked_bdaa7e_idx',
            old_name='analytics_linkclick_link_clicked_idx',
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='event_type',
            field=models.CharField(choices=[('pageview', 'Page View'), ('click', 'Click'), ('form_submit', 'Form Submit'), ('scroll', 'Scroll'), ('session_end', 'Session End'), ('custom', 'Custom')], default='pageview', max_length=20),
        ),
    ]
