# Generated by Django 5.1.15 on 2026-04-12 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_keywordalert_keywordalertevent_competitordomain_competitorkeywordrank"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="platformcontent",
            new_name="analytics_p_website_825adc_idx",
            old_name="analytics_plat_website_platform_idx",
        ),
        migrations.AlterField(
            model_name="competitordomain",
            name="domain",
            field=models.CharField(help_text="e.g. competitor.com (no https://)", max_length=300),
        ),
        migrations.AlterField(
            model_name="competitordomain",
            name="name",
            field=models.CharField(blank=True, help_text="Friendly label", max_length=200),
        ),
        migrations.AlterField(
            model_name="keywordalert",
            name="threshold",
            field=models.IntegerField(
                default=3, help_text="Trigger when rank changes by at least this many positions."
            ),
        ),
        migrations.AlterField(
            model_name="keywordalert",
            name="tracked_keyword",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to apply this alert to all tracked keywords.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="analytics.trackedkeyword",
            ),
        ),
        migrations.AlterField(
            model_name="keywordalertevent",
            name="change",
            field=models.IntegerField(
                help_text="Positive = improved (rank went up), negative = declined."
            ),
        ),
        migrations.AlterField(
            model_name="keywordscanconfig",
            name="is_auto_scan_enabled",
            field=models.BooleanField(
                default=True, help_text="Automatically re-scan the DOM at the configured interval."
            ),
        ),
        migrations.AlterField(
            model_name="keywordscanconfig",
            name="scan_depth",
            field=models.IntegerField(
                default=5, help_text="Maximum number of pages to crawl per scan."
            ),
        ),
        migrations.AlterField(
            model_name="keywordscanconfig",
            name="scan_interval_hours",
            field=models.IntegerField(
                default=24,
                help_text="How often to re-scan (in hours). Common values: 1, 6, 24, 168.",
            ),
        ),
        migrations.AlterField(
            model_name="platformcontent",
            name="content",
            field=models.TextField(help_text="Full text of the post or article"),
        ),
        migrations.AlterField(
            model_name="platformcontent",
            name="extracted_keywords",
            field=models.JSONField(
                default=list, help_text='[{"keyword": "...", "density": 1.2, "count": 3}, ...]'
            ),
        ),
        migrations.AlterField(
            model_name="platformcontent",
            name="platform_post_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Platform-native post ID to prevent duplicates.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="platformcontent",
            name="title",
            field=models.CharField(
                blank=True, help_text="Post title or first line", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="platformcontent",
            name="url",
            field=models.URLField(
                blank=True, help_text="Link to the original post", max_length=2000
            ),
        ),
    ]
