# Generated by Django 5.1.15 on 2026-06-05 16:51

from django.db import migrations, models


def backfill_last_activity(apps, schema_editor):
    """Seed last_activity from started_at so existing sessions are not all
    treated as expired the moment the new inactivity logic goes live."""
    Session = apps.get_model("analytics", "Session")
    Session.objects.filter(last_activity__isnull=True).update(
        last_activity=models.F("started_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0010_drop_keyword_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="last_activity",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_last_activity, migrations.RunPython.noop),
    ]
