# Generated by Django 5.1.15 on 2026-06-05 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0011_session_last_activity"),
        ("websites", "0007_website_competitors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_email", models.CharField(blank=True, max_length=254)),
                ("website_id_raw", models.CharField(db_index=True, max_length=64)),
                ("path", models.CharField(max_length=300)),
                ("method", models.CharField(default="GET", max_length=8)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("accessed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_accesslog",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["website_id_raw", "-accessed_at"],
                        name="analytics_a_website_f07279_idx",
                    ),
                    models.Index(
                        fields=["user", "-accessed_at"], name="analytics_a_user_id_c24d79_idx"
                    ),
                ],
            },
        ),
    ]
