# Generated by Django 5.1.15 on 2026-05-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_studio", "0002_auto_phase4_drift"),
        ("content_studio", "0002_drop_claim_mismatch_fk"),
    ]

    operations = []
