# Generated by Django 5.1.15 on 2026-05-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="citation",
            new_name="citations_c_audit_i_751b7f_idx",
            old_name="citations_c_audit_i_idx",
        ),
        migrations.RenameIndex(
            model_name="citation",
            new_name="citations_c_apex_do_680fa2_idx",
            old_name="citations_c_apex_i_idx",
        ),
        migrations.RenameIndex(
            model_name="citation",
            new_name="citations_c_result__3d4e4e_idx",
            old_name="citations_c_result_i_idx",
        ),
        migrations.RenameIndex(
            model_name="sourceinfluencesnapshot",
            new_name="citations_s_provide_d64397_idx",
            old_name="citations_s_provid_i_idx",
        ),
        migrations.RenameIndex(
            model_name="sourceinfluencesnapshot",
            new_name="citations_s_website_0920b5_idx",
            old_name="citations_s_websit_i_idx",
        ),
    ]
