# Generated by Django 5.1.15 on 2026-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0002_auto_phase2_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="reference_count",
            field=models.IntegerField(default=0),
        ),
    ]
