# Generated by Django 5.1.15 on 2026-07-04 22:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0003_citation_reference_count"),
        ("websites", "0007_website_competitors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceScan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("provider", models.CharField(default="perplexity", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("results_count", models.IntegerField(default=0)),
                ("analyzed_count", models.IntegerField(default=0)),
                ("brands", models.JSONField(blank=True, default=list)),
                ("own_brand_present", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_scans",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "citations_sourcescan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceScanResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rank", models.IntegerField()),
                ("url", models.URLField(max_length=2000)),
                ("domain", models.CharField(db_index=True, max_length=300)),
                (
                    "source_class",
                    models.CharField(
                        choices=[
                            ("reddit", "Reddit"),
                            ("quora", "Quora"),
                            ("stackoverflow", "Stack Overflow"),
                            ("news", "News"),
                            ("wikipedia", "Wikipedia"),
                            ("blog", "Blog"),
                            ("forum", "Forum"),
                            ("docs", "Documentation"),
                            ("social", "Social"),
                            ("youtube", "YouTube"),
                            ("podcast", "Podcast"),
                            ("gov", "Government"),
                            ("edu", "Education"),
                            ("your_site", "Your Site"),
                            ("competitor_site", "Competitor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("serp_title", models.CharField(blank=True, max_length=500)),
                ("serp_snippet", models.TextField(blank=True)),
                ("fetch_status", models.CharField(default="skipped", max_length=16)),
                ("content_kind", models.CharField(blank=True, max_length=16)),
                ("word_count", models.IntegerField(default=0)),
                ("brands", models.JSONField(blank=True, default=list)),
                ("analysis_error", models.CharField(blank=True, max_length=300)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="citations.sourcescan",
                    ),
                ),
            ],
            options={
                "db_table": "citations_sourcescanresult",
                "ordering": ["rank"],
            },
        ),
        migrations.AddIndex(
            model_name="sourcescan",
            index=models.Index(
                fields=["website", "-created_at"], name="citations_s_website_b18269_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sourcescanresult",
            unique_together={("scan", "rank")},
        ),
    ]
