# Generated by Django 5.1.15 on 2026-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0004_sourcescan_sourcescanresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcescanresult",
            name="last_updated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcescanresult",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcescanresult",
            name="relevance_note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sourcescanresult",
            name="relevant",
            field=models.BooleanField(default=True),
        ),
    ]
