# Generated by Django 5.1.15 on 2026-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0006_sourcescan_seed_urls_source_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescan',
            name='stages',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
