# Generated by Django 5.1.15 on 2026-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0007_sourcescan_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescan',
            name='serp_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sourcescanresult',
            name='discovery',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sourcescanresult',
            name='platform_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
