# Generated by Django 5.1.15 on 2026-08-28 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0008_sourcescan_serp_features_sourcescanresult_discovery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceScanEngineAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('not_configured', 'Not configured'), ('failed', 'Failed')], default='failed', max_length=16)),
                ('answer_text', models.TextField(blank=True)),
                ('brands', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('cited_ranks', models.JSONField(blank=True, default=list)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_answers', to='citations.sourcescan')),
            ],
            options={
                'db_table': 'citations_sourcescanengineanswer',
                'ordering': ['provider'],
                'unique_together': {('scan', 'provider')},
            },
        ),
    ]
