# Generated by Django 5.1.15 on 2026-03-06 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_chatmessage",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentCalendarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("topic", models.CharField(blank=True, max_length=300)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog", "Blog Post"),
                            ("social", "Social Media"),
                            ("email", "Email"),
                            ("video", "Video"),
                        ],
                        default="blog",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("status", models.CharField(default="scheduled", max_length=20)),
                ("ai_generated", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_entries",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_contentcalendarentry",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="NicheAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("clusters", models.JSONField(default=list)),
                ("opportunities", models.JSONField(default=list)),
                ("positioning", models.JSONField(default=dict)),
                ("summary", models.TextField(blank=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niche_analyses",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_nicheanalysis",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("30", "30 Days"), ("60", "60 Days"), ("90", "90 Days")],
                        default="30",
                        max_length=5,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("raw_response", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("completion_pct", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_strategy",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("action_type", models.CharField(blank=True, max_length=50)),
                ("estimated_impact", models.CharField(blank=True, max_length=20)),
                ("estimated_time_minutes", models.IntegerField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ai_reasoning", models.TextField(blank=True)),
                ("week_number", models.IntegerField(default=1)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="strategy.strategy",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_action",
                "ordering": ["week_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="MorningBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("content", models.TextField()),
                ("metrics_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="morning_briefs",
                        to="websites.website",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_morningbrief",
                "ordering": ["-date"],
                "unique_together": {("website", "date")},
            },
        ),
    ]
