# Generated by Django 5.1.15 on 2026-03-26 23:41

import core.encryption.field_encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_segment_alter_user_plan_organization_and_more"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                            ("telegram", "Telegram"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("webhook_url", core.encryption.field_encryption.EncryptedTextField()),
                ("channel_name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("schedule_time", models.TimeField(default="09:00")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("realtime", "Real-time"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "message_format",
                    models.CharField(
                        choices=[("summary", "Summary"), ("detailed", "Detailed")],
                        default="summary",
                        max_length=20,
                    ),
                ),
                ("notify_daily_report", models.BooleanField(default=True)),
                ("notify_hot_leads", models.BooleanField(default=True)),
                ("notify_trend_digest", models.BooleanField(default=True)),
                ("notify_milestones", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_connections",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_integrationconnection",
                "unique_together": {("user", "platform")},
            },
        ),
    ]
