# Generated by Django 5.1.15 on 2026-08-18 23:48

from django.db import migrations, models


def delete_telegram_connections(apps, schema_editor):
    """Telegram support is removed. Sends never worked (TELEGRAM_BOT_TOKEN was
    never declared in settings), so any stored rows are inert - delete them."""
    IntegrationConnection = apps.get_model("notifications", "IntegrationConnection")
    IntegrationConnection.objects.filter(platform="telegram").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_integrationconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconnection',
            name='external_channel_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='external_team_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='platform',
            field=models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=20),
        ),
        migrations.RunPython(
            delete_telegram_connections, migrations.RunPython.noop
        ),
    ]
