# Generated by Django 5.1.15 on 2026-08-29 02:19

import core.encryption.field_encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_integrationconnection_external_channel_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_e164', core.encryption.field_encryption.EncryptedTextField()),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('opted_out', 'Opted out')], db_index=True, default='pending', max_length=16)),
                ('verification_code_hash', models.CharField(blank=True, max_length=64)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('alert_security', models.BooleanField(default=True)),
                ('alert_visibility_drop', models.BooleanField(default=True)),
                ('allow_replies', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_smssubscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_hash', 'status'], name='notificatio_phone_h_39d015_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'phone_hash'), name='uniq_sms_user_phone')],
            },
        ),
    ]
