# Generated by Django 5.1.15 on 2026-08-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_smssubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='platform',
            field=models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('teams', 'Microsoft Teams')], db_index=True, max_length=20),
        ),
    ]
