# Generated by Django 5.1.15 on 2026-09-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_integrationconnection_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssubscription',
            name='pulse_digest',
            field=models.BooleanField(default=False),
        ),
    ]
